const $=(s,p=document)=>p.querySelector(s);const $$=(s,p=document)=>[...p.querySelectorAll(s)];
const header=$('[data-header]'), menuBtn=$('[data-menu-toggle]'), menu=$('[data-mobile-menu]');
window.addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>60),{passive:true});
menuBtn.addEventListener('click',()=>{const open=menu.classList.toggle('open');menuBtn.classList.toggle('open',open);menuBtn.setAttribute('aria-expanded',open);menu.setAttribute('aria-hidden',!open)});
$$('.mobile-menu a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');menuBtn.classList.remove('open');menuBtn.setAttribute('aria-expanded','false');menu.setAttribute('aria-hidden','true')}));
const io=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting?e.target.classList.add('is-visible'):e.target.classList.remove('is-visible'),{threshold:.12,rootMargin:'0px 0px -8% 0px'}));
$$('.reveal-up,.reveal-clip').forEach(el=>io.observe(el));
let raf=0;function parallax(){const y=scrollY;$$('[data-parallax]').forEach(el=>{const r=el.getBoundingClientRect();if(r.bottom>0&&r.top<innerHeight){const delta=(innerHeight/2-(r.top+r.height/2));el.style.transform=`translate3d(0,${delta*parseFloat(el.dataset.parallax)}px,0) scale(1.05)`}});raf=0}window.addEventListener('scroll',()=>{if(!raf)raf=requestAnimationFrame(parallax)},{passive:true});parallax();
const cursor=$('.cursor');if(cursor&&matchMedia('(pointer:fine)').matches){let cx=innerWidth/2,cy=innerHeight/2,tx=cx,ty=cy;addEventListener('pointermove',e=>{tx=e.clientX;ty=e.clientY});function move(){cx+=(tx-cx)*.16;cy+=(ty-cy)*.16;cursor.style.left=cx+'px';cursor.style.top=cy+'px';requestAnimationFrame(move)}move();$$('[data-cursor]').forEach(el=>{el.addEventListener('mouseenter',()=>{cursor.classList.add('active');cursor.querySelector('span').textContent=el.dataset.cursor});el.addEventListener('mouseleave',()=>cursor.classList.remove('active'))});$$('a,button').forEach(el=>{if(!el.hasAttribute('data-cursor')){el.addEventListener('mouseenter',()=>cursor.classList.add('link'));el.addEventListener('mouseleave',()=>cursor.classList.remove('link'))}})}
const gallery=$$('.gallery-item'),light=$('[data-lightbox]'),lightImg=$('[data-lightbox-img]'),lightTitle=$('[data-lightbox-title]');let current=0;
function show(i){current=(i+gallery.length)%gallery.length;const b=gallery[current];lightImg.src=b.dataset.full;lightImg.alt=b.getAttribute('aria-label')||'';lightTitle.textContent=b.dataset.title||''}
function openLight(i){show(i);light.classList.add('open');light.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeLight(){light.classList.remove('open');light.setAttribute('aria-hidden','true');document.body.style.overflow=''}
gallery.forEach((g,i)=>g.addEventListener('click',()=>openLight(i)));$('[data-close]').addEventListener('click',closeLight);$('[data-prev]').addEventListener('click',()=>show(current-1));$('[data-next]').addEventListener('click',()=>show(current+1));light.addEventListener('click',e=>{if(e.target===light)closeLight()});addEventListener('keydown',e=>{if(!light.classList.contains('open'))return;if(e.key==='Escape')closeLight();if(e.key==='ArrowLeft')show(current-1);if(e.key==='ArrowRight')show(current+1)});
$$('.acc-trigger').forEach(btn=>btn.addEventListener('click',()=>{const open=btn.closest('.acc-item').classList.toggle('open');btn.setAttribute('aria-expanded',open)}));
